config/routes.rb
Rails.application.routes.draw do
  get "public/show"
  resources :comments
  resources :photos
  resources :relationships
  devise_for :users
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "/manifest.json" => "rails/pwa#manifest"
  get "/service-worker.js" => "rails/pwa#service_worker"

  # Defines the root path route ("/")
  root "public#index"
  get "/love/:id", to: "public#index", as: :public_relationship
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy


  def duration_parts
    total_seconds = (Time.zone.now - start_date.to_time).to_i

    days = total_seconds / (3600 * 24)
    hours = (total_seconds % (3600 * 24)) / 3600
    minutes = (total_seconds % 3600) / 60
    seconds = total_seconds % 60

    { days: days, hours: hours, minutes: minutes, seconds: seconds }
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :set_relationship, only: %i[ show edit update destroy ]

  # GET /relationships or /relationships.json
  def index
    @relationships = Relationship.all
  end

  # GET /relationships/1 or /relationships/1.json
  def show
  end

  # GET /relationships/new
  def new
    @relationship = Relationship.new
  end

  # GET /relationships/1/edit
  def edit
  end

  # POST /relationships or /relationships.json
  def create
    @relationship = Relationship.new(relationship_params)

    respond_to do |format|
      if @relationship.save
        format.html { redirect_to @relationship, notice: "Relationship was successfully created." }
        format.json { render :show, status: :created, location: @relationship }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /relationships/1 or /relationships/1.json
  def update
    respond_to do |format|
      if @relationship.update(relationship_params)
        format.html { redirect_to @relationship, notice: "Relationship was successfully updated." }
        format.json { render :show, status: :ok, location: @relationship }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /relationships/1 or /relationships/1.json
  def destroy
    @relationship.destroy!

    respond_to do |format|
      format.html { redirect_to relationships_path, status: :see_other, notice: "Relationship was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_relationship
      @relationship = Relationship.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def relationship_params
      params.expect(relationship: [ :start_date, :user_id ])
    end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_form.html.erb
<%= form_with(model: relationship) do |form| %>
  <% if relationship.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(relationship.errors.count, "error") %> prohibited this relationship from being saved:</h2>

      <ul>
        <% relationship.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :start_date, style: "display: block" %>
    <%= form.date_field :start_date %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.collection_select :user_id, User.all, :id, :name, class: "border rounded px-3 py-2" %>

  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/relationships/_relationship.html.erb
<div id="<%= dom_id relationship %>" class="bg-white dark:bg-gray-800 p-4 rounded-lg shadow mb-4">
  <p class="text-gray-800 dark:text-gray-200">
    <strong class="text-gray-700 dark:text-gray-300">Start date:</strong>
    <%= relationship.start_date %>
  </p>

  <p class="text-gray-800 dark:text-gray-200">
    <strong class="text-gray-700 dark:text-gray-300">User:</strong>
    <%= relationship.user.name %>
  </p>

</div>

app/views/relationships/edit.html.erb
<% content_for :title, "Editing relationship" %>

<h1>Editing relationship</h1>

<%= render "form", relationship: @relationship %>

<br>

<div>
  <%= link_to "Show this relationship", @relationship %> |
  <%= link_to "Back to relationships", relationships_path %>
</div>

app/views/relationships/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Relationships" %>

<h1>Relationships</h1>

<div id="relationships">
  <% @relationships.each do |relationship| %>
    <%= render relationship %>
    <p>
      <%= link_to "Show this relationship", relationship %>
    </p>
  <% end %>
</div>

<%= link_to "New relationship", new_relationship_path %>

app/views/relationships/new.html.erb
<% content_for :title, "New relationship" %>

<h1>New relationship</h1>

<%= render "form", relationship: @relationship %>

<br>

<div>
  <%= link_to "Back to relationships", relationships_path %>
</div>

app/views/relationships/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @relationship %>

<div>
  <%= link_to "Edit this relationship", edit_relationship_path(@relationship) %> |
  <%= link_to "Back to relationships", relationships_path %>

  <%= button_to "Destroy this relationship", @relationship, method: :delete %>
</div>