config/routes.rb
Rails.application.routes.draw do
  get "public/show"
  resources :comments
  resources :photos
  resources :relationships
  devise_for :users
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "/manifest.json" => "rails/pwa#manifest"
  get "/service-worker.js" => "rails/pwa#service_worker"

  # Defines the root path route ("/")
  root "public#index"
  get "/love/:id", to: "public#index", as: :public_relationship
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :relationship
  has_one_attached :image
  has_many :comments, dependent: :destroy
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # This line defines a Ruby class named PhotosController, which inherits from ApplicationController.

  private
    def set_photo
      @photo = Photo.find(params[:id])
    end

    def photo_params
      params.require(:photo).permit(:title, :relationship_id, :image)
    end

  public

  before_action :authenticate_user!, except: [ :index, :show ]
  before_action :set_photo, only: %i[ show edit update destroy ]

  # GET /photos or /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1 or /photos/1.json
  def show; end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit; end

  # POST /photos or /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: "Photo was successfully created." }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1 or /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: "Photo was successfully updated." }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1 or /photos/1.json
  def destroy
    @photo.destroy!

    respond_to do |format|
      format.html { redirect_to photos_path, status: :see_other, notice: "Photo was successfully destroyed." }
      format.json { head :no_content }
    end
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_with(model: photo) do |form| %>
  <% if photo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
        <% photo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>

  <div class="mb-4">
    <%= form.label :relationship_id, "Relacionamento" %>
    <%= form.collection_select :relationship_id, Relationship.all, :id, :start_date, class: "border rounded px-3 py-2" %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/photos/_photo.html.erb
<div id="<%= dom_id photo %>" class="bg-white dark:bg-gray-800 p-4 rounded-lg shadow mb-4">
  <p class="text-gray-800 dark:text-gray-200">
    <strong class="text-gray-700 dark:text-gray-300">Title:</strong>
    <%= photo.title %>
  </p>

  <p class="text-gray-800 dark:text-gray-200">
    <strong class="text-gray-700 dark:text-gray-300">Relationship:</strong>
    <%= photo.relationship_id %>
  </p>

  <p class="text-gray-800 dark:text-gray-200">
    <strong class="text-gray-700 dark:text-gray-300">Image:</strong>
    <%= image_tag photo.image, class: "rounded-xl shadow-md w-full max-w-md mx-auto dark:shadow-gray-700" if photo.image.attached? %>
  </p>
</div>

app/views/photos/edit.html.erb
<% content_for :title, "Editing photo" %>

<h1>Editing photo</h1>

<%= render "form", photo: @photo %>

<br>

<div>
  <%= link_to "Show this photo", @photo %> |
  <%= link_to "Back to photos", photos_path %>
</div>

app/views/photos/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Photos" %>

<h1>Photos</h1>

<div id="photos">
  <% @photos.each do |photo| %>
    <%= render photo %>
    <p>
      <%= link_to "Show this photo", photo %>
    </p>
  <% end %>
</div>

<%= link_to "New photo", new_photo_path %>

app/views/photos/new.html.erb
<% content_for :title, "New photo" %>

<h1>New photo</h1>

<%= render "form", photo: @photo %>

<br>

<div>
  <%= link_to "Back to photos", photos_path %>
</div>

app/views/photos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @photo %>

<h3>Comentários</h3>
<% @photo.comments.each do |comment| %>
  <p><strong><%= comment.user.email %>:</strong> <%= comment.body %></p>
<% end %>



<div>
  <%= link_to "Edit this photo", edit_photo_path(@photo) %> |
  <%= link_to "Back to photos", photos_path %>

  <%= button_to "Destroy this photo", @photo, method: :delete %>
</div>