config/routes.rb
Rails.application.routes.draw do
  get "public/show"
  resources :comments
  resources :photos
  resources :relationships
  devise_for :users
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "/manifest.json" => "rails/pwa#manifest"
  get "/service-worker.js" => "rails/pwa#service_worker"

  # Defines the root path route ("/")
  root "public#index"
  get "/love/:id", to: "public#index", as: :public_relationship
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="<%= cookies[:theme] || 'dark' %>">
  <head>
    <title><%= content_for(:title) || "Love Counter App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <link href="https://fonts.googleapis.com/css2?family=EB+Garamond&display=swap" rel="stylesheet">

    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-stone-200 text-black dark:bg-gothic-background dark:text-gothic-text">
  <% if user_signed_in? %>
    <%= render 'shared/sidebar' %>
  <% end %>

  <main class="flex-1 p-1">
    <%= yield %>
  </main>

  </body>
</html>